image: ghcr.io/olix0r/ort:v0.1.12

# # If the protocol ports are unset (or set to 0), then the load deployment won't be created and
# the service won't expose the port.
protocols:
  grpc:
    enabled: true
    port: 8070
    loadFlags: {}
  http:
    enabled: true
    port: 8080
    loadFlags: {}
  tcp:
    enabled: false
    port: 8090
    loadFlags: {}

load:
  #log: info
  replicas: 1
  threads: 1
  linkerd: {}
  flags: {}
    #clients: 2
    #concurrencyLimit: 100
    #requestLimit: 100
    #requestLimitWindow: 1s
    #responseSizes: 0=1ms,100=1s

server:
  #log: debug
  threads: 1
  services: 1
  replicas: 1
  split: false
  linkerd: {}
  flags: {}
  configs: {}

linkerd:
  inject: enabled
  config: {}
    #proxyImage: ...
    #proxyVersion: ...

viz:
  enabled: false
  grafana:
    image: docker.io/grafana/grafana:7.3.4
    linkerd: {}
  prometheus:
    image: docker.io/prom/prometheus:v2.23.0
    linkerd: {}
    flags:
      storage.tsdb.path: /data
      storage.tsdb.retention.time: 1w
      config.file: /etc/prometheus/prometheus.yml
      log.level: info
    globalConfig:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s
