[workspace]
members = [
    ".",
    "load",
    "server",
]

[package]
name = "ortiofay"
version = "0.1.0"
authors = ["Oliver Gould <ver@buoyant.io>"]
edition = "2018"
publish = false

[features]
default = ["load", "server"]
load = ["ortiofay-load"]
server = ["ortiofay-server"]
rustfmt = ["ortiofay-load/rustfmt", "ortiofay-server/rustfmt"]

[dependencies]
ortiofay-load = { path = "./load", optional = true }
ortiofay-server = { path = "./server", optional = true }
structopt = "0.3"
tokio = { version = "0.3", features = ["macros", "rt-multi-thread", "time"] }
tokio-compat-02 = "0.1"
tracing-subscriber = "0.2"
