[workspace]
members = [
    ".",
    "load",
    "server",
]

[package]
name = "ort"
version = "0.1.1"
authors = ["Oliver Gould <ver@buoyant.io>"]
edition = "2018"
publish = false

[features]
default = ["load", "server"]
load = ["ort-load"]
server = ["ort-server"]
rustfmt = ["ort-load/rustfmt", "ort-server/rustfmt"]

[dependencies]
ort-load = { path = "./load", optional = true }
ort-server = { path = "./server", optional = true }
structopt = "0.3"
tokio = { version = "0.3", features = ["macros", "rt-multi-thread", "time"] }
tokio-compat-02 = "0.1"
tracing-subscriber = "0.2"
