---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reports
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/run/ortiofay

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports
spec:
  selector:
    matchLabels:
      app: ortiofay
      role: reports
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ortiofay
        role: reports
    spec:
      volumes:
        - name: reports
          persistentVolumeClaim:
            claimName: reports
      containers:
      - image: busybox
        name: echo
        volumeMounts:
          - mountPath: /reports
            name: reports
        command: ["/bin/sh"]
        args:
          - -c
          - |-
            while true ; do date ; ls -la /reports ; sleep 20 ; done
