---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: ortiofay
    role: server
spec:
  selector:
    matchLabels:
      app: ortiofay
      role: server
  template:
    metadata:
      labels:
        app: ortiofay
        role: server
    spec:
      containers:
        - image: fortio/fortio:latest
          name: fortio
          args:
            - server
            - -grpc-port
            - "8079"
            - -http-port
            - "8080"
          ports:
            - name: grpc
              containerPort: 8079
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "1"

---
kind: Service
apiVersion: v1
metadata:
  name: server
  labels:
    app: ortiofay
    role: server
spec:
  type: ClusterIP
  selector:
    app: ortiofay
    role: server
  ports:
    - name: grpc
      port: 8079
      targetPort: 8079
    - name: http
      port: 8080
      targetPort: 8080
