image: ghcr.io/olix0r/ort:v0.1.7

# # If the protocol ports are unset (or set to 0), then the load deployment won't be created and
# the service won't expose the port.
protocols:
  grpc: 8070
  http: 8080

load:
  #log: info
  replicas: 1
  threads: 3
  linkerd: {}
  flags: {}
    #requestsPerClient: 1
    #httpClose: false
    #concurrencyLimit: 0
    #requestLimit: 0
    #requestLimitWindow: 1s
    #responseSizes: 0=1024,100=1048576

server:
  #log: debug
  threads: 1
  services: 1
  replicas: 1
  linkerd: {}

linkerd:
  inject: enabled
  config: {}
    #proxyImage: ...
    #proxyVersion: ...
