image: ghcr.io/olix0r/ortiofay:v6

load:
  protocols:
    grpc: true
    http: true
  replicas: 1
  linkerdInject: true
  clients: 1
  streams: 1
  #concurrencyLimit: 0
  #requestLimit: 0
  #requestLimitWindow: 1s
  #responseSizes: 0=1024,100=1048576
  linkerd: {}

server:
  services: 1
  replicas: 1
  linkerdInject: true
  linkerd: {}

linkerd: {}
  #proxyImage: ...
  #proxyVersion: ...
