{{- if .Values.viz.enabled -}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app: ort
    ort.olix0r.net/role: grafana
{{- end }}
