{{- $ns := .Release.Namespace}}
{{- $img := .Values.image}}
{{- $linkerd := .Values.linkerd}}
{{- $services := int .Values.server.services | default 1}}
{{- $load := .Values.load}}
{{- range $proto, $enabled := .Values.load.protocols}}
{{-   if $enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ortiofay
    ortiofay.olix0r.net/role: load
    ortiofay.olix0r.net/protocol: {{$proto}}
  name: load-{{$proto}}
  namespace: {{$ns}}
spec:
  replicas: {{int $load.replicas}}
  selector:
    matchLabels:
      app: ortiofay
      ortiofay.olix0r.net/role: load
      ortiofay.olix0r.net/protocol: {{$proto}}
  template:
    metadata:
      labels:
        app: ortiofay
        ortiofay.olix0r.net/role: load
        ortiofay.olix0r.net/protocol: {{$proto}}
      annotations:
        linkerd.io/inject: {{$load.linkerdInject | default false | ternary "enabled" "disabled"}}
{{-     if $linkerd.proxyImage}}
        config.linkerd.io/proxy-image: {{$linkerd.proxyImage}}
{{-     end}}
{{-     if $linkerd.proxyVersion}}
        config.linkerd.io/proxy-version: {{$linkerd.proxyVersion}}
{{-     end}}
    spec:
      containers:
        - name: main
          image: {{$img}}
          args:
            - load
            - --clients={{$load.clients | default 1}}
            - --concurrency={{$load.concurrency | default 1}}
{{-     if $load.requestLimit }}
            - --request-limit={{$load.requestLimit}}
            - --request-limit-window={{$load.requestLimitWindow | default "1s"}}
{{-     end}}
{{-     if $load.totalRequests }}
            - --total-request={{$load.totalRequests}}
{{-     end}}
{{-     if $load.responseSizes }}
            - --response-sizes={{$load.responseSizes}}
{{-     end}}
{{-     range $i, $e := until $services}}
            - {{printf "%s://server-%03d:8070" $proto $i}}
{{-     end}}
{{-   end}}
{{- end}}
