{{- $ns := .Release.Namespace }}
{{- $img := .Values.image }}
{{- $services := int .Values.server.services | default 1}}
{{- $load := .Values.load }}
{{- $linkerd := deepCopy .Values.linkerd | merge $load.linkerd }}
{{- range $proto, $port := .Values.protocols }}
{{-   if $port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ort
    ort.olix0r.net/role: load
    ort.olix0r.net/protocol: {{ $proto }}
  name: load-{{ $proto }}
  namespace: {{ $ns }}
spec:
  replicas: {{ int $load.replicas }}
  selector:
    matchLabels:
      app: ort
      ort.olix0r.net/role: load
      ort.olix0r.net/protocol: {{ $proto }}
  template:
    metadata:
      labels:
        app: ort
        ort.olix0r.net/role: load
        ort.olix0r.net/protocol: {{ $proto }}
      annotations:
{{ $linkerd | include "ort.linkerd" | indent 8 }}
    spec:
      containers:
        - name: main
          image: {{ $img }}
          env:
            - name: RUST_LOG
              value: {{ $load.log | default "info" | quote }}
          {{- if eq $linkerd.inject "disabled" }}
            - name: LINKERD_DISABLED
              value: "true"
          {{- end }}
          args:
          {{- if $load.threads }}
            - --threads={{ $load.threads }}
          {{- end }}
            - load
          {{- range $f, $v := $load.flags }}
            - --{{ kebabcase $f }}={{ $v }}
          {{- end }}
          {{- range $i, $e := until $services }}
            - {{ printf "%s://server-%03d:%d" $proto $i (int $port) }}
          {{- end }}
{{-   end }}
{{- end }}
