{{- $ns := .Release.Namespace }}
{{- $img := .Values.image }}
{{- $replicas := int .Values.server.replicas }}
{{- $linkerd := .Values.linkerd }}
{{- $server := .Values.server }}
{{- $protocols := .Values.protocols }}
{{- range $i, $e := until (.Values.server.services | int) }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ort
  name: server-{{printf "%03d" $i}}
  namespace: {{$ns}}
spec:
  selector:
    app: ort
    ort.olix0r.net/role: server
    ort.olix0r.net/instance: {{quote $i}}
  ports:
  {{- range $name, $port := $protocols }}
  {{-   if $port }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      name: {{ $name }}
  {{-   end }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ort
    ort.olix0r.net/role: server
    ort.olix0r.net/instance: {{quote $i}}
  name: server-{{printf "%03d" $i}}
  namespace: {{$ns}}
spec:
  selector:
    matchLabels:
      app: ort
      ort.olix0r.net/role: server
      ort.olix0r.net/instance: {{quote $i}}
  replicas: {{$replicas}}
  template:
    metadata:
      labels:
        app: ort
        ort.olix0r.net/role: server
        ort.olix0r.net/instance: {{quote $i}}
      annotations:
{{ deepCopy $linkerd | merge $server.linkerd | include "ort.linkerd" | indent 8 }}
    spec:
      containers:
        - name: main
          image: {{$img}}
          args:
          {{- if $server.threads }}
            - threads={{ $server.threads }}
          {{- end }}
            - server
          ports:
          {{- range $name, $port := $protocols }}
          {{-   if $port }}
            - protocol: TCP
              containerPort: {{ $port }}
              name: {{ $name }}
          {{-   end }}
          {{- end }}
{{- end}}
